# Generated by Django 2.1.5 on 2019-01-25 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_auto_20190124_2115'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'waiting'), (2, 'verified'), (3, 'rejected')], default=1, verbose_name='Status')),
                ('duration_total', models.DurationField(verbose_name='Duration')),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('date_from', models.DateTimeField(verbose_name='Best date for me')),
                ('date_to', models.DateTimeField()),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('services', models.ManyToManyField(to='main.Service', verbose_name='Services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
