# Generated by Django 2.1.5 on 2019-02-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'WAITING'), (2, 'VERIFIED'), (3, 'REJECTED')], default=1, verbose_name='Status'),
        ),
    ]
