# Generated by Django 2.1.5 on 2019-01-24 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type_of', models.CharField(max_length=255, verbose_name='Type')),
                ('duration', models.DurationField(choices=[(datetime.timedelta(0, 900), '15 min'), (datetime.timedelta(0, 1800), '30 min'), (datetime.timedelta(0, 2700), '45 min'), (datetime.timedelta(0, 3600), '1 hour'), (datetime.timedelta(0, 4500), '1 hour 15 minutes'), (datetime.timedelta(0, 5400), '1 hour 30 minutes'), (datetime.timedelta(0, 6300), '1 hour 30 minutes'), (datetime.timedelta(0, 7200), '2 hours')], verbose_name='Duration')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
            ],
        ),
    ]
