# Generated by Django 2.1.5 on 2019-01-24 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(0, 900), '15 min'), (datetime.timedelta(0, 1800), '30 min'), (datetime.timedelta(0, 2700), '45 min'), (datetime.timedelta(0, 3600), '1 hour'), (datetime.timedelta(0, 4500), '1 hour 15 minutes'), (datetime.timedelta(0, 5400), '1 hour 30 minutes'), (datetime.timedelta(0, 6300), '1 hour 45 minutes'), (datetime.timedelta(0, 7200), '2 hours')], verbose_name='Duration'),
        ),
    ]
